# Generated by Django 5.2.9 on 2025-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="progresso",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Progresso do projeto em % (0 a 100)"
            ),
        ),
    ]
