# Generated by Django 5.2.9 on 2025-12-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0002_projeto_progresso"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Capa ou logo do projeto",
                null=True,
                upload_to="projetos_capa/",
            ),
        ),
    ]
