# Generated by Django 5.2.9 on 2025-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0003_projeto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="demo",
            field=models.URLField(
                blank=True, help_text="Link de demonstração (ex: vídeo, deploy)"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="docs",
            field=models.URLField(blank=True, help_text="Link da documentação"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="repo",
            field=models.URLField(
                blank=True, help_text="Link do repositório (ex: GitHub)"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link principal do projeto (ex: site)"
            ),
        ),
    ]
