# Generated by Django 5.2.9 on 2025-12-15 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "plataforma",
                    models.CharField(
                        blank=True, help_text="Ex: Udemy, Alura, YouTube", max_length=60
                    ),
                ),
                ("instrutor", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField(blank=True, help_text="Link do curso")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Capa do curso",
                        null=True,
                        upload_to="cursos_capa/",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "progresso",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Progresso do curso em % (0 a 100)"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("ordem", models.PositiveSmallIntegerField(default=1)),
                (
                    "duracao",
                    models.CharField(
                        blank=True, help_text="Ex: 10m, 1h20", max_length=20
                    ),
                ),
                ("assistido", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, help_text="Link da aula")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
