# Generated by Django 5.2.9 on 2025-12-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("codigo", "Código"),
                            ("dica", "Dica"),
                            ("script", "Script"),
                            ("referencia", "Referência"),
                            ("outro", "Outro"),
                        ],
                        default="codigo",
                        max_length=20,
                    ),
                ),
                ("code", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        blank=True, help_text="Ex: python, bash, js", max_length=30
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Separe por vírgula", max_length=120
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("reused", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
